### ISSUE TITLE
Collection isn't a collection

### ISSUE THREAD

**Issue by mattstauffer** [Zn4rK/php-withings#11]
The thing named `Collection` is actually more like an entity, or a value object. Collections--especially in the Laravel sense--are like a grouping of many similar items. So the SubscriptionList `profiles` parameter would be a collection; it's many profiles. Or, the array of `groups` that's attached to a measure could be a collection instead of an array. But most of the things called "Collection" here are really a single class of objects with a particular set of properties, etc. which would mean they're not really a collection.

I'd be happy to write a PR, but I want to be sure that you're interested in it first; I think they should be converted to be entities (naming difference) with their properties set explicitly rather than dynamically; e.g.

```php
<?php
class Measure extends Entity
{
    /** @var Carbon **/
    public $updatedtime;

    /** @var MeasureGroupCollection */
    public $groups;

    // etcetera...
}
```

**Comment by Zn4rK** [comment]
Closing this one.
