### ISSUE TITLE
Unable to install using composer

### ISSUE THREAD

**Issue by jisuo** [Zn4rK/php-withings#16]
Getting this message:

"Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for paxx/withings dev-master -> satisfiable by paxx/withings[dev-master].
    - paxx/withings dev-master requires chrisnharvey/oauth1 dev-master -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems."

On chrisnharvey/oauth1 it says "Deprecated: Use league/oauth1-client." https://github.com/thephpleague/oauth1-client

**Comment by Zn4rK** [comment]
It seems like chrisnharvey/oauth1 has been deprecated. That's too bad. I'll try to find the time to fix this during the weekend. No promises though.

**Comment by Zn4rK** [comment]
Fixed!
