### ISSUE TITLE
Laravel 5

### ISSUE THREAD

**Issue by toxic0berliner** [Zn4rK/php-withings#21]
Hello,

I'm trying to write my chart app  with laravel5, but I get an error loading this API. It complaints that the serviceProvider does not implement a package method.

I havebread online that Laravel 5 has changed its packaging,but as I'm very new to Laravel, I'm not able to fix this.. 

Any help would be welcome.

**Comment by Zn4rK** [comment]
Have you installed socialite?
https://github.com/laravel/socialite

**Comment by Zn4rK** [comment]
This package should still work with Laravel 5.
