### ISSUE TITLE
getActivites() not working

### ISSUE THREAD

**Issue by Sonemai** [Zn4rK/php-withings#24]
I can't get getActivites working. It's not returning any values the same way getMeasures() is. I've tried to recreate the foreach loop used in the example.
$config is the same used for measures (example).
$api = new WithingsApi($config);
$Auser = $api->getUser();

foreach($Auser->getActivites() as $activites) {
    echo $activites->getCreatedAt() . ': <br>';

    echo 'Steps: ' . $activites->getSteps() . ' steps';
    echo '<hr>';

}

**Comment by Zn4rK** [comment]
Since Withings latest Android update I can't get their app to work (so I can't add any activities). Do you get any data from the request at all? 

print_r($activity) on this line to check:
https://github.com/Zn4rK/php-withings/blob/master/src/Paxx/Withings/Api.php#L178

**Comment by Sonemai** [comment]
Hey. Thank you for your reply. I tested printing the $activity. Indeed it returned activities in array and in json.  Still don't quite understand why getActivites isn't returning the same info. I managed to get getActivity() to print an empty json like: [{},{},{},{},{},{},{},{},{},{},{}]

**Comment by Sonemai** [comment]
Wait a second... now I managed to get the filled json without the print_r. (Exactly same code as before). Some dark magic going on.

**Comment by Zn4rK** [comment]
I think it's an issue with Withings. I don't really know why you are getting inconsistent results. Try breaking it down a bit more, and see if you get any data from Withings with the API.
